// Actions Types
export const SET_CANDIDATES = "SET_CANDIDATES"
export const SET_QUESTIONS = "SET_QUESTIONS"
export const SET_APPLICATIONS = "SET_APPLICATIONS"
export const SET_INITIAL_STATE = "SET_INITIAL_STATE"
export const UPDATE_APPLICATION = "UPDATE_APPLICATION"